version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: CET
    open-pull-requests-limit: 15
    target-branch: master
